export const SCHEMA = `
CREATE TABLE IF NOT EXISTS songs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT,
  suggested_color TEXT DEFAULT '#1e1b4b',
  number INTEGER,
  language TEXT
);

CREATE TABLE IF NOT EXISTS song_lines (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  song_id INTEGER NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  line_number INTEGER NOT NULL,
  text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS cultos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  date TEXT,
  background_color TEXT DEFAULT '#1e1b4b'
);

CREATE TABLE IF NOT EXISTS slots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  culto_id INTEGER NOT NULL REFERENCES cultos(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  type TEXT NOT NULL,
  label TEXT NOT NULL,
  song_id INTEGER REFERENCES songs(id),
  content TEXT
);
`;
